#statisticPath: "/home/natasha/pharmacy_reference/statistics"
#emailDownloadPath: "/home/natasha/pharmacy_reference/file_download"

statisticPath: "/workspace/statistic"
emailDownloadPath: "/workspace/download"

emailAddress: "sprav074@mail.ru"
emailPassword: "Spravka654321"


users:
  admin:
    username: admin
    password: Spravka_010484
  user1:
    username: user1
    password: Cupic01
  user2:
    username: user2
    password: Cupic02
  user3:
    username: user3
    password: Cupic03
  user4:
    username: user4
    password: Cupic04

