statisticPath: "/home/natasha/IdeaProjects/Справка/pharmacy_reference/src/main/resources/statistics"
emailDownloadPath: "/home/natasha/IdeaProjects/Справка/pharmacy_reference/src/main/resources/file_download"

emailAddress: "sprav074@mail.ru"
emailPassword: "Spravka654321"

users:
  admin:
    username: admin
    password: Spravka654321
  user1:
    username: user1
    password: user
  user2:
    username: user2
    password: user
  user3:
    username: user3
    password: user
  user4:
    username: user4
    password: user