statisticPath : "/home/natasha/IdeaProjects/Справка/pharmacy_reference/src/main/resources/statistics"
emailDownloadPath : "/home/natasha/IdeaProjects/Справка/pharmacy_reference/src/main/resources/file_download"

emailAddress : "sprav074@mail.ru"
password : "Spravka654321"
